# Generated by Django 5.0.1 on 2024-02-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_program',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Баллы программы лояльности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Изображение пользователя'),
        ),
    ]
