# Generated by Django 5.0.1 on 2024-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_loyalty_program_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loyalty_program',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=256, null=True, verbose_name='Баллы программы лояльности'),
        ),
    ]
