# Generated by Django 5.0.1 on 2024-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_loyalty_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loyalty_program',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы программы лояльности'),
        ),
    ]
