# Generated by Django 5.0.3 on 2024-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создаётся', 'Создаётся'), ('Доставляется', 'Доставляется'), ('Доставлен', 'Доставлен')], default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
