# Generated by Django 5.0.3 on 2024-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_ordercountpast'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBoolean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BooleanField(default=False)),
            ],
        ),
    ]
