# Generated by Django 5.0.1 on 2024-02-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
