# Generated by Django 5.0.1 on 2024-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
