# Generated by Django 5.0.3 on 2024-05-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_count_orderboolean_bool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderBoolean',
        ),
    ]
