# Generated by Django 5.0.1 on 2024-02-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_add',
            field=models.BooleanField(default=False, verbose_name='Просто функция'),
        ),
    ]
