# Generated by Django 5.0.1 on 2024-02-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_is_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_add',
            field=models.BooleanField(default=False, editable=False, verbose_name='Просто функция, не трогать'),
        ),
    ]
