# Generated by Django 5.0.1 on 2024-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_is_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deduct_points',
            field=models.BooleanField(default=False, verbose_name='Списывать баллы?'),
        ),
    ]
