# Generated by Django 5.0.1 on 2024-03-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderitem_points_deducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deduct_points',
            field=models.BooleanField(default=False, verbose_name='Баллы списаны'),
        ),
    ]
