# Generated by Django 5.0.1 on 2024-03-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_orderitem_points_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Суммарная стоимость'),
        ),
    ]
