# Generated by Django 5.0.1 on 2024-03-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_delivery_date_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_timestamp',
            field=models.TimeField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
    ]
