# Generated by Django 5.0.1 on 2024-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_delivery_date_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата-время доставки'),
        ),
    ]
