# Generated by Django 5.0.1 on 2024-03-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_delivery_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
    ]
