# Generated by Django 5.0.1 on 2024-03-12 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_order_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 2, 3, 46, 40, tzinfo=datetime.timezone.utc), verbose_name='Дата создания заказа'),
        ),
    ]
