# Generated by Django 5.0.3 on 2024-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_pieces',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
