# Generated by Django 5.0.1 on 2024-03-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_on_or_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='on_or_off',
            field=models.BooleanField(default=True, verbose_name='Продаётся'),
        ),
    ]
