# Generated by Django 5.0.3 on 2024-06-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_number_of_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_pieces',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Количество'),
        ),
    ]
