# Generated by Django 5.0.3 on 2024-07-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_min_quantity_by_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_quantity_by_weight',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=8, verbose_name='Мин. кол-во по массе'),
        ),
    ]
