# Generated by Django 5.0.3 on 2024-07-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Масса'),
        ),
    ]
